### ISSUE TITLE
Bazel workspace broken

### ISSUE THREAD

**Issue by SpencerC** [google/copybara#197]
Following 869c8b1e0467257dc4819cf7f1e58bd464849477, builds in my macos Bazel workspace fail with the error:
```
Error in read: Not a regular file: /Users/spencer/<myproject>/external/third_party/jcommander.BUILD
```

**Comment by hsudhof** [comment]
I cannot reproduce this issue on either MacOs or linux - what bazel version are you using?

**Comment by SpencerC** [comment]
5.1.1-homebrew

**Comment by smocherla-brex** [comment]
+1, facing this issue here on my Mac.
```
INFO: Repository 'JCommander' used the following cache hits instead of downloading the corresponding file.
 * Hash 'e7ed3cf09f43d0d0a083f1b3243c6d1b45139a84a61c6356504f9b7aa14554fc' for https://github.com/cbeust/jcommander/archive/05254453c0a824f719bd72dac66fa686525752a5.zip
If the definition of 'JCommander' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'JCommander':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_smocherla/11a2024f80aa076c86aa5567e9fefb88/external/bazel_tools/tools/build_defs/repo/http.bzl", line 121, column 28, in _http_archive_impl
		workspace_and_buildfile(ctx)
	File "/private/var/tmp/_bazel_smocherla/11a2024f80aa076c86aa5567e9fefb88/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 61, column 41, in workspace_and_buildfile
		ctx.file("BUILD.bazel", ctx.read(ctx.attr.build_file))
Error in read: Not a regular file: /Users/smocherla/repos/multirepo-migrations/external/third_party/jcommander.BUILD
ERROR: /Users/smocherla/repos/multirepo-migrations/WORKSPACE:12:22: fetching http_archive rule //external:JCommander: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_smocherla/11a2024f80aa076c86aa5567e9fefb88/external/bazel_tools/tools/build_defs/repo/http.bzl", line 121, column 28, in _http_archive_impl
		workspace_and_buildfile(ctx)
	File "/private/var/tmp/_bazel_smocherla/11a2024f80aa076c86aa5567e9fefb88/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 61, column 41, in workspace_and_buildfile
		ctx.file("BUILD.bazel", ctx.read(ctx.attr.build_file))
Error in read: Not a regular file: /Users/smocherla/repos/multirepo-migrations/external/third_party/jcommander.BUILD
```

**Comment by hsudhof** [comment]
Interesting. I cannot reproduce this so far.

**Comment by hsudhof** [comment]
I would recommend updating bazel first.
