### ISSUE TITLE
DateTime parsing error

### ISSUE THREAD

**Issue by emanuelez** [google/copybara#23]
While evaluating Copybara I ran into this:

```
bazel-bin/java/com/google/copybara/copybara migrate copy.bara.sky --force
Copybara source mover (Version: Unknown version)
Task: Git Destination: Fetching: https://github.com/<undisclosed>.git master
WARN: Git Destination: 'master' doesn't exist in 'https://github.com/<undisclosed>.git'
WARN: Cannot find last imported revision, but proceeding because of --force flag
java.time.format.DateTimeParseException: Text '%aI' could not be parsed at index 0
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1947)
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1849)
	at java.time.ZonedDateTime.parse(ZonedDateTime.java:597)
	at java.time.ZonedDateTime.parse(ZonedDateTime.java:582)
	at com.google.copybara.git.GitRepository$LogCmd.parseLog(GitRepository.java:1351)
	at com.google.copybara.git.GitRepository$LogCmd.run(GitRepository.java:1307)
	at com.google.copybara.git.ChangeReader.run(ChangeReader.java:73)
	at com.google.copybara.git.GitOrigin$ReaderImpl.changes(GitOrigin.java:222)
	at com.google.copybara.git.GitOrigin$ReaderImpl.changes(GitOrigin.java:120)
	at com.google.copybara.WorkflowRunHelper.getChanges(WorkflowRunHelper.java:313)
	at com.google.copybara.WorkflowMode$1.run(WorkflowMode.java:56)
	at com.google.copybara.Workflow.run(Workflow.java:192)
	at com.google.copybara.Copybara.run(Copybara.java:58)
	at com.google.copybara.Main.runInternal(Main.java:171)
	at com.google.copybara.Main.run(Main.java:106)
	at com.google.copybara.Main.main(Main.java:85)
ERROR: Unexpected error (please file a bug): Text '%aI' could not be parsed at index 0 (java.time.format.DateTimeParseException: Text '%aI' could not be parsed at index 0)
```

**Comment by mikelalcon** [comment]
Could you try git 2.10 or later?

**Comment by emanuelez** [comment]
That seems to have worked. Thanks!
