### ISSUE TITLE
Unable to build hermetically / without local java

### ISSUE THREAD

**Issue by Zemnmez** [google/copybara#279]
I'm trying to build copybara as per the instructions in the readme. I get the following error:

```
thomas@DESKTOP-B82ERE8 ~/d/monorepo> bazel run //bin/host/copybara                                                                                                                                                                      1
WARNING: Option 'experimental_remote_build_event_upload' is deprecated: Use --remote_build_event_upload instead
INFO: Invocation ID: 998e0d77-4c04-4ae9-af1c-5ba8877e95ef
INFO: Streaming build results to: https://app.buildbuddy.io/invocation/998e0d77-4c04-4ae9-af1c-5ba8877e95ef
WARNING: Option 'experimental_remote_build_event_upload' is deprecated: Use --remote_build_event_upload instead
INFO: Repository maven instantiated at:
  /home/thomas/devel/monorepo/WORKSPACE:211:28: in <toplevel>
  /home/thomas/.cache/bazel/_bazel_thomas/a41610ee02ad9c69b13020a7f1cf3deb/external/com_github_google_copybara/repositories.maven.bzl:66:10: in copybara_maven_repositories
  /home/thomas/.cache/bazel/_bazel_thomas/a41610ee02ad9c69b13020a7f1cf3deb/external/bazel_tools/tools/build_defs/repo/utils.bzl:240:18: in maybe
  /home/thomas/.cache/bazel/_bazel_thomas/a41610ee02ad9c69b13020a7f1cf3deb/external/rules_jvm_external/private/rules/maven_install.bzl:104:19: in maven_install
Repository rule coursier_fetch defined at:
  /home/thomas/.cache/bazel/_bazel_thomas/a41610ee02ad9c69b13020a7f1cf3deb/external/rules_jvm_external/coursier.bzl:1180:33: in <toplevel>
INFO: repository @@maven' used the following cache hits instead of downloading the corresponding file.
 * Hash 'af986793a515d500ab2d35f8d2aecd656e764504b789b66d7e1a0b727a124c44' for https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
 * Hash 'a51d36968dcbdeabb3142c6f5cf9b401a65dc3a095f3144bd0c118d5bb192753' for https://github.com/stedolan/jq/releases/download/jq-1.6/jq-win64.exe
 * Hash '076de041cbebc0a1272b84f1e69f6da5df4961847850b95cb3dfa3f776145225' for https://github.com/coursier/coursier/releases/download/v2.0.16/coursier.jar
 * Hash '5c0a0a3ea600f302ee458b30317425dd9632d1ad8882259fcaf4e9b868b2b1ef' for https://github.com/stedolan/jq/releases/download/jq-1.6/jq-osx-amd64
If the definition of 'repository @@maven' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'maven':
   Traceback (most recent call last):
        File "/home/thomas/.cache/bazel/_bazel_thomas/a41610ee02ad9c69b13020a7f1cf3deb/external/rules_jvm_external/coursier.bzl", line 827, column 13, in _coursier_fetch_impl
                fail("Unable to run coursier: " + exec_result.stderr)
Error in fail: Unable to run coursier: /home/thomas/.cache/bazel/_bazel_thomas/a41610ee02ad9c69b13020a7f1cf3deb/external/maven/coursier: 25: exec: java: not found
ERROR: /home/thomas/devel/monorepo/WORKSPACE:211:28: fetching coursier_fetch rule //external:maven: Traceback (most recent call last):
        File "/home/thomas/.cache/bazel/_bazel_thomas/a41610ee02ad9c69b13020a7f1cf3deb/external/rules_jvm_external/coursier.bzl", line 827, column 13, in _coursier_fetch_impl
                fail("Unable to run coursier: " + exec_result.stderr)
Error in fail: Unable to run coursier: /home/thomas/.cache/bazel/_bazel_thomas/a41610ee02ad9c69b13020a7f1cf3deb/external/maven/coursier: 25: exec: java: not found
INFO: Repository rules_java~7.3.2~toolchains~remotejdk21_linux instantiated at:
  <builtin>: in <toplevel>
Repository rule http_archive defined at:
  /home/thomas/.cache/bazel/_bazel_thomas/a41610ee02ad9c69b13020a7f1cf3deb/external/bazel_tools/tools/build_defs/repo/http.bzl:384:31: in <toplevel>
INFO: Repository rules_java~7.3.2~toolchains~remotejdk11_linux instantiated at:
  <builtin>: in <toplevel>
Repository rule http_archive defined at:
  /home/thomas/.cache/bazel/_bazel_thomas/a41610ee02ad9c69b13020a7f1cf3deb/external/bazel_tools/tools/build_defs/repo/http.bzl:384:31: in <toplevel>
ERROR: no such package '@@maven//': Unable to run coursier: /home/thomas/.cache/bazel/_bazel_thomas/a41610ee02ad9c69b13020a7f1cf3deb/external/maven/coursier: 25: exec: java: not found
ERROR: /home/thomas/.cache/bazel/_bazel_thomas/a41610ee02ad9c69b13020a7f1cf3deb/external/com_github_google_copybara/third_party/BUILD:159:13: @@com_github_google_copybara//third_party:jsr305 depends on @@maven//:com_google_code_findbugs_jsr305 in repository @@maven which failed to fetch. no such package '@@maven//': Unable to run coursier: /home/thomas/.cache/bazel/_bazel_thomas/a41610ee02ad9c69b13020a7f1cf3deb/external/maven/coursier: 25: exec: java: not found
ERROR: Analysis of target '//bin/host/copybara:copybara' failed; build aborted: Analysis failed
INFO: Elapsed time: 18.451s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
ERROR: Build did NOT complete successfully
ERROR: Build failed. Not running target
INFO: Streaming build results to: https://app.buildbuddy.io/invocation/998e0d77-4c04-4ae9-af1c-5ba8877e95ef
FAILED: 
    Fetching https://mirror.bazel.build/cdn.azul.com/zulu/bin/zulu11.66.15-ca-jdk11.0.20-linux_x64.tar.gz; 91.2 MiB (47.8%) 17s
    Fetching https://mirror.bazel.build/cdn.azul.com/zulu/bin/zulu21.28.85-ca-jdk21.0.0-linux_x64.tar.gz; 58.6 MiB (28.9%) 16s
    Fetching repository @@io_bazel; starting
    Fetching /home/thomas/.cache/bazel/_bazel_thomas/a41610ee02ad9c69b13020a7f1cf3deb/external/io_bazel; Extracting 47e29b7c7c37a49a3e64324a72551b1d73d803b4.zip
```

Here's the minimal commit:

https://github.com/zemn-me/monorepo/pull/4623/commits/3553503ed88c6a099bc8e950e8e14d578be2759e

Thank you for your help.

**Comment by Zemnmez** [comment]
This is my first time trying and I have been unable to make it work.ThanksThomasOn 12 Feb 2024, at 09:53, Mikel Alcon ***@***.***> wrote:﻿
Do you mean that with that minimal commit it doesn't happen anymore?

**Comment by mikelalcon** [comment]
Please follow the instructions in https://github.com/google/copybara?tab=readme-ov-file#getting-started-using-copybara. First item [Install JDK 11](https://www.oracle.com/java/technologies/downloads/#java11).
